### ISSUE TITLE
File mode not specified when creating /etc/sudoers.d/99-jupyterhub-user

### ISSUE THREAD

**Issue by jocelynpicard** [ComputeCanada/puppet-jupyterhub#23]
```
[root@jupyterhub-dev ~]# visudo -c
/etc/sudoers: parsed OK
/etc/sudoers.d/99-jupyterhub-user: bad permissions, should be mode 0440
```
This is a problem when the sudo module is used after the jupyterhub module. The sudo module performs a validation and fails.

Jocelyn

**Comment by cmd-ntrf** [comment]
Thankfs. Fixed in commit a14c731c9172ccc57d260a012503d546e23b224f and released in v3.8.3.
