### ISSUE TITLE
Supporting LTI Authenticator

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/puppet-jupyterhub#62]
https://github.com/jupyterhub/ltiauthenticator/
LTI Authenticator seems to be the way to go to integrate a Jupyter Hub into various LMS, it would be great if puppet-jupyterhub could be configured to support this.

Replacing https://github.com/ComputeCanada/puppet-magic_castle/issues/371

**Comment by cmd-ntrf** [comment]
Closed by #72
